baseURL = "https://magkociuba.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Magdalena Kociuba"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Magdalena Kociuba"
author = "Designed by Magdalena Kociuba"
description = "Logistics Engineer and International Management Specialist"
profilePicture = "images/profile_pic_1.jpg"
keywords = ""
favicon = "favicons/"
customCss = []


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".


## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/magdalena-kociuba-a432061a5/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/magkociuba"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/magdakociuba"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:magdalena.kociuba95@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "About me"
  identifier = "About me"
  weight = 100
  url = "/about/"

  [[menu.main]]
  name = "Experience"
  weight = 200
  identifier = "Experience"
  url = "/experience/"

